# Generated by Django 2.0.7 on 2021-05-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='idcs.Idc', verbose_name='所在机房'),
        ),
    ]
